apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $NAMESPACE
  name: $APPNAME
  labels:
    app: $APPNAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APPNAME
  template:
    metadata:
      labels:
        app: $APPNAME
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: $IMAGEPULLSECRETS
      volumes:
        - name: config-env-volume
          configMap:
            name: $CONFIGMAPNAME
            defaultMode: 420
            items:
              - key: 'ENV_FILE'
                path: '.env.production'
      containers:
        - name: $APPNAME
          image: $FULLIMAGENAME
          imagePullPolicy: Always
          volumeMounts:
            - name: config-env-volume
              mountPath: /app/.env.production
              readOnly: true
              subPath: .env.production
          env:
            - name: CAMPAIGN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: CAMPAIGN_API_KEY
            - name: AZURE_AD_SECRET
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: AZURE_AD_SECRET
            - name: SPW_PORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: SPW_PORTAL_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: JWT_SECRET
            - name: MASTER_DATA_CS_KEY
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: MASTER_DATA_CS_KEY
            - name: REPORT_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: REPORT_SERVICE_API_KEY
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: $KUBESECRETNAME
                  key: NEW_RELIC_LICENSE_KEY
          ports:
            - containerPort: 31006
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: '0.3'
              memory: '512Mi'
            limits:
              cpu: '0.5'
              memory: '1Gi'

---
apiVersion: v1
kind: Service
metadata:
  name: $APPNAME
spec:
  ports:
    - name: http
      port: 31006
      protocol: TCP
      targetPort: 3000
      nodePort: 31006
  selector:
    app: $APPNAME
  type: NodePort

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: $APPNAME-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $APPNAME
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 30
          periodSeconds: 60
